# Generated by Django 3.0.4 on 2020-04-09 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_user_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('shopid', models.AutoField(primary_key=True, serialize=False)),
                ('shop_name', models.CharField(default='', max_length=30)),
                ('shop_owner', models.CharField(max_length=30)),
                ('shop_address', models.CharField(max_length=140)),
                ('shop_category', models.PositiveSmallIntegerField(choices=[(1, 'Medicines'), (2, 'Groceries'), (3, 'Dairy'), (4, 'Other Needs')], default=4)),
            ],
        ),
    ]
