# Generated by Django 3.0.4 on 2020-04-09 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20200409_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slots',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User'),
        ),
    ]
