# Generated by Django 3.0.4 on 2020-04-14 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20200414_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slots',
            name='slot_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='slots',
            name='slot_time',
            field=models.TimeField(),
        ),
    ]
